"""
    Traction Guest API

    The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.  # Getting Started If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).  We will also add you to our Slack channel where you can ask questions and get further help.  # Terms and Conditions Please visit: [https://tractionguest.com/tos/api/](https://tractionguest.com/tos/api/)  # Versioning This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.  * The `Major` number increments when potentially incompatible changes are made. * The `Minor` number increments when backwards-compatible additions are made. * The `Patch` number increments when backwards-compatible bug-fixes are made.   # noqa: E501

    The version of the OpenAPI document: 0.15.0
    Contact: support@tractionguest.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from TractionGuest.api_client import ApiClient, Endpoint as _Endpoint
from TractionGuest.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from TractionGuest.model.errors_list import ErrorsList
from TractionGuest.model.package import Package
from TractionGuest.model.package_create_params import PackageCreateParams
from TractionGuest.model.package_update_params import PackageUpdateParams
from TractionGuest.model.paginated_packages_list import PaginatedPackagesList


class PackagesApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __create_package(
            self,
            **kwargs
        ):
            """Create package  # noqa: E501

            Creates a [Package] entity by extracting information about the recipient and carrier from the given image file.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.create_package(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                package_create_params (PackageCreateParams): Parameters for creating a package. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Package
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.create_package = _Endpoint(
            settings={
                'response_type': (Package,),
                'auth': [],
                'endpoint_path': '/packages',
                'operation_id': 'create_package',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'package_create_params',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'package_create_params':
                        (PackageCreateParams,),
                },
                'attribute_map': {
                },
                'location_map': {
                    'package_create_params': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__create_package
        )

        def __delete_package(
            self,
            package_id,
            **kwargs
        ):
            """delete_package  # noqa: E501

            Delete a pacakge  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_package(package_id, async_req=True)
            >>> result = thread.get()

            Args:
                package_id (str):

            Keyword Args:
                idempotency_key (str): An optional idempotency key to allow for repeat API requests. Any API request with this key will only be executed once, no matter how many times it's submitted. We store idempotency keys for only 24 hours. Any `Idempotency-Key` shorter than 10 characters will be ignored. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['package_id'] = \
                package_id
            return self.call_with_http_info(**kwargs)

        self.delete_package = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/packages/{package_id}',
                'operation_id': 'delete_package',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'package_id',
                    'idempotency_key',
                ],
                'required': [
                    'package_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'package_id':
                        (str,),
                    'idempotency_key':
                        (str,),
                },
                'attribute_map': {
                    'package_id': 'package_id',
                    'idempotency_key': 'Idempotency-Key',
                },
                'location_map': {
                    'package_id': 'path',
                    'idempotency_key': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_package
        )

        def __get_package(
            self,
            package_id,
            **kwargs
        ):
            """Get Package  # noqa: E501

            Gets the details of a single instance of a Package  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_package(package_id, async_req=True)
            >>> result = thread.get()

            Args:
                package_id (str):

            Keyword Args:
                include (str): A list of comma-separated related models to include . [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Package
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['package_id'] = \
                package_id
            return self.call_with_http_info(**kwargs)

        self.get_package = _Endpoint(
            settings={
                'response_type': (Package,),
                'auth': [],
                'endpoint_path': '/packages/{package_id}',
                'operation_id': 'get_package',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'package_id',
                    'include',
                ],
                'required': [
                    'package_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'package_id':
                        (str,),
                    'include':
                        (str,),
                },
                'attribute_map': {
                    'package_id': 'package_id',
                    'include': 'include',
                },
                'location_map': {
                    'package_id': 'path',
                    'include': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_package
        )

        def __get_packages(
            self,
            **kwargs
        ):
            """Get packages  # noqa: E501

            Gets a list of [Package] entities.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_packages(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                location_ids (str): A comma separated list of Location ids for filtering. i.e. '1,2,3' Will return all packages from all locations if none are specified. [optional]
                limit (int): Limits the results to a specified number, defaults to 50. [optional] if omitted the server will use the default value of 50
                offset (int): Offsets the results to a specified number, defaults to 0. [optional] if omitted the server will use the default value of 0
                include (str): A list of comma-separated related models to include. Possible values: 'recipient', 'location', 'image'. [optional]
                picked_up (bool): Filters packages by their \"picked_up\" state... [optional]
                query (str): Searches for packages by recipient name. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaginatedPackagesList
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.get_packages = _Endpoint(
            settings={
                'response_type': (PaginatedPackagesList,),
                'auth': [],
                'endpoint_path': '/packages',
                'operation_id': 'get_packages',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'location_ids',
                    'limit',
                    'offset',
                    'include',
                    'picked_up',
                    'query',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                    'limit',
                    'offset',
                ]
            },
            root_map={
                'validations': {
                    ('limit',): {

                        'inclusive_minimum': 1,
                    },
                    ('offset',): {

                        'inclusive_minimum': 0,
                    },
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'location_ids':
                        (str,),
                    'limit':
                        (int,),
                    'offset':
                        (int,),
                    'include':
                        (str,),
                    'picked_up':
                        (bool,),
                    'query':
                        (str,),
                },
                'attribute_map': {
                    'location_ids': 'location_ids',
                    'limit': 'limit',
                    'offset': 'offset',
                    'include': 'include',
                    'picked_up': 'picked_up',
                    'query': 'query',
                },
                'location_map': {
                    'location_ids': 'query',
                    'limit': 'query',
                    'offset': 'query',
                    'include': 'query',
                    'picked_up': 'query',
                    'query': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_packages
        )

        def __update_package(
            self,
            package_id,
            **kwargs
        ):
            """Update Package  # noqa: E501

            Update/Edit information about a Package.  picked_up - changes the package_state to picked up and assigns non null value to picked_up_at  recipient_id - update the package's intended recipient. Changes package_state to 'recipient_matched' if a match hasn't been found and notifies host about their package via email. A previous recipient will stop getting notifications  carrier_name - change/update the package's carrier/courier information   # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.update_package(package_id, async_req=True)
            >>> result = thread.get()

            Args:
                package_id (str):

            Keyword Args:
                idempotency_key (str): An optional idempotency key to allow for repeat API requests. Any API request with this key will only be executed once, no matter how many times it's submitted. We store idempotency keys for only 24 hours. Any `Idempotency-Key` shorter than 10 characters will be ignored. [optional]
                package_update_params (PackageUpdateParams): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Package
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['package_id'] = \
                package_id
            return self.call_with_http_info(**kwargs)

        self.update_package = _Endpoint(
            settings={
                'response_type': (Package,),
                'auth': [],
                'endpoint_path': '/packages/{package_id}',
                'operation_id': 'update_package',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'package_id',
                    'idempotency_key',
                    'package_update_params',
                ],
                'required': [
                    'package_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'package_id':
                        (str,),
                    'idempotency_key':
                        (str,),
                    'package_update_params':
                        (PackageUpdateParams,),
                },
                'attribute_map': {
                    'package_id': 'package_id',
                    'idempotency_key': 'Idempotency-Key',
                },
                'location_map': {
                    'package_id': 'path',
                    'idempotency_key': 'header',
                    'package_update_params': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__update_package
        )
