"""
    Traction Guest API

    The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.  # Getting Started If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).  We will also add you to our Slack channel where you can ask questions and get further help.  # Terms and Conditions Please visit: [https://tractionguest.com/tos/api/](https://tractionguest.com/tos/api/)  # Versioning This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.  * The `Major` number increments when potentially incompatible changes are made. * The `Minor` number increments when backwards-compatible additions are made. * The `Patch` number increments when backwards-compatible bug-fixes are made.   # noqa: E501

    The version of the OpenAPI document: 0.15.0
    Contact: support@tractionguest.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from TractionGuest.api_client import ApiClient, Endpoint as _Endpoint
from TractionGuest.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from TractionGuest.model.errors_list import ErrorsList
from TractionGuest.model.paginated_watchlist_list import PaginatedWatchlistList
from TractionGuest.model.watchlist import Watchlist
from TractionGuest.model.watchlist_create_params import WatchlistCreateParams


class WatchlistsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __create_watchlist(
            self,
            watchlist_create_params,
            **kwargs
        ):
            """Create Watchlist  # noqa: E501

            Create a new `Watchlist` record. Please note, every action taken against this endpoint is recorded in the audit log.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.create_watchlist(watchlist_create_params, async_req=True)
            >>> result = thread.get()

            Args:
                watchlist_create_params (WatchlistCreateParams): The new `Watchlist` to create

            Keyword Args:
                idempotency_key (str): An optional idempotency key to allow for repeat API requests. Any API request with this key will only be executed once, no matter how many times it's submitted. We store idempotency keys for only 24 hours. Any `Idempotency-Key` shorter than 10 characters will be ignored. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Watchlist
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['watchlist_create_params'] = \
                watchlist_create_params
            return self.call_with_http_info(**kwargs)

        self.create_watchlist = _Endpoint(
            settings={
                'response_type': (Watchlist,),
                'auth': [],
                'endpoint_path': '/watchlists',
                'operation_id': 'create_watchlist',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'watchlist_create_params',
                    'idempotency_key',
                ],
                'required': [
                    'watchlist_create_params',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'watchlist_create_params':
                        (WatchlistCreateParams,),
                    'idempotency_key':
                        (str,),
                },
                'attribute_map': {
                    'idempotency_key': 'Idempotency-Key',
                },
                'location_map': {
                    'watchlist_create_params': 'body',
                    'idempotency_key': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__create_watchlist
        )

        def __delete_watchlist(
            self,
            watchlist_id,
            **kwargs
        ):
            """Deletes a Watchlist  # noqa: E501

            Deletes a single instance of `Watchlist`  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_watchlist(watchlist_id, async_req=True)
            >>> result = thread.get()

            Args:
                watchlist_id (str):

            Keyword Args:
                idempotency_key (str): An optional idempotency key to allow for repeat API requests. Any API request with this key will only be executed once, no matter how many times it's submitted. We store idempotency keys for only 24 hours. Any `Idempotency-Key` shorter than 10 characters will be ignored. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['watchlist_id'] = \
                watchlist_id
            return self.call_with_http_info(**kwargs)

        self.delete_watchlist = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/watchlists/{watchlist_id}',
                'operation_id': 'delete_watchlist',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'watchlist_id',
                    'idempotency_key',
                ],
                'required': [
                    'watchlist_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'watchlist_id':
                        (str,),
                    'idempotency_key':
                        (str,),
                },
                'attribute_map': {
                    'watchlist_id': 'watchlist_id',
                    'idempotency_key': 'Idempotency-Key',
                },
                'location_map': {
                    'watchlist_id': 'path',
                    'idempotency_key': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_watchlist
        )

        def __get_watchlist(
            self,
            watchlist_id,
            **kwargs
        ):
            """Get a Watchlist  # noqa: E501

            Gets the details of a single instance of a `Watchlist`.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_watchlist(watchlist_id, async_req=True)
            >>> result = thread.get()

            Args:
                watchlist_id (str):

            Keyword Args:
                include (str): A list of comma-separated related models to include. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Watchlist
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['watchlist_id'] = \
                watchlist_id
            return self.call_with_http_info(**kwargs)

        self.get_watchlist = _Endpoint(
            settings={
                'response_type': (Watchlist,),
                'auth': [],
                'endpoint_path': '/watchlists/{watchlist_id}',
                'operation_id': 'get_watchlist',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'watchlist_id',
                    'include',
                ],
                'required': [
                    'watchlist_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'watchlist_id':
                        (str,),
                    'include':
                        (str,),
                },
                'attribute_map': {
                    'watchlist_id': 'watchlist_id',
                    'include': 'include',
                },
                'location_map': {
                    'watchlist_id': 'path',
                    'include': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_watchlist
        )

        def __get_watchlists(
            self,
            **kwargs
        ):
            """List all Watchlists  # noqa: E501

            Gets a list of all `Watchlist` entities.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_watchlists(async_req=True)
            >>> result = thread.get()


            Keyword Args:
                limit (int): Limits the results to a specified number, defaults to 50. [optional]
                offset (int): Offsets the results to a specified number, defaults to 0. [optional]
                query (str): Query the results by `first_name`, `last_name`, `email`, `colour`, and `notes` all at once.. [optional]
                with_colours (str): A comma separated list of case-insensitive colour values. i.e., `red`, `green`, `yellow`, and `orange`. [optional]
                include (str): A list of comma-separated related models to include. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                PaginatedWatchlistList
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            return self.call_with_http_info(**kwargs)

        self.get_watchlists = _Endpoint(
            settings={
                'response_type': (PaginatedWatchlistList,),
                'auth': [],
                'endpoint_path': '/watchlists',
                'operation_id': 'get_watchlists',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'limit',
                    'offset',
                    'query',
                    'with_colours',
                    'include',
                ],
                'required': [],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'limit':
                        (int,),
                    'offset':
                        (int,),
                    'query':
                        (str,),
                    'with_colours':
                        (str,),
                    'include':
                        (str,),
                },
                'attribute_map': {
                    'limit': 'limit',
                    'offset': 'offset',
                    'query': 'query',
                    'with_colours': 'with_colours',
                    'include': 'include',
                },
                'location_map': {
                    'limit': 'query',
                    'offset': 'query',
                    'query': 'query',
                    'with_colours': 'query',
                    'include': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_watchlists
        )

        def __update_watchlist(
            self,
            watchlist_id,
            watchlist_create_params,
            **kwargs
        ):
            """Update a Watchlist  # noqa: E501

            Update an existing `Watchlist` record. Every operation against this endpoint is recorded in the audit log.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.update_watchlist(watchlist_id, watchlist_create_params, async_req=True)
            >>> result = thread.get()

            Args:
                watchlist_id (str):
                watchlist_create_params (WatchlistCreateParams): The watchlist record attributes to update

            Keyword Args:
                idempotency_key (str): An optional idempotency key to allow for repeat API requests. Any API request with this key will only be executed once, no matter how many times it's submitted. We store idempotency keys for only 24 hours. Any `Idempotency-Key` shorter than 10 characters will be ignored. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Watchlist
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['watchlist_id'] = \
                watchlist_id
            kwargs['watchlist_create_params'] = \
                watchlist_create_params
            return self.call_with_http_info(**kwargs)

        self.update_watchlist = _Endpoint(
            settings={
                'response_type': (Watchlist,),
                'auth': [],
                'endpoint_path': '/watchlists/{watchlist_id}',
                'operation_id': 'update_watchlist',
                'http_method': 'PUT',
                'servers': None,
            },
            params_map={
                'all': [
                    'watchlist_id',
                    'watchlist_create_params',
                    'idempotency_key',
                ],
                'required': [
                    'watchlist_id',
                    'watchlist_create_params',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'watchlist_id':
                        (str,),
                    'watchlist_create_params':
                        (WatchlistCreateParams,),
                    'idempotency_key':
                        (str,),
                },
                'attribute_map': {
                    'watchlist_id': 'watchlist_id',
                    'idempotency_key': 'Idempotency-Key',
                },
                'location_map': {
                    'watchlist_id': 'path',
                    'watchlist_create_params': 'body',
                    'idempotency_key': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__update_watchlist
        )
